//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Text Left.
        /// </summary>
        public static string AlignTextLeft {
            get {
                return ResourceManager.GetString("AlignTextLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Text Right.
        /// </summary>
        public static string AlignTextRight {
            get {
                return ResourceManager.GetString("AlignTextRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All unsaved changes will be discarded if you leave this page..
        /// </summary>
        public static string AllUnsafedChangesWillBeDiscardedIfYouLeaveThisPage {
            get {
                return ResourceManager.GetString("AllUnsafedChangesWillBeDiscardedIfYouLeaveThisPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternatively you can leave this field blank..
        /// </summary>
        public static string AlternativelyYouCanLeaveThisFieldBlank {
            get {
                return ResourceManager.GetString("AlternativelyYouCanLeaveThisFieldBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternatively you can leave this field blank for now..
        /// </summary>
        public static string AlternativelyYouCanLeaveThisFieldBlankForNow {
            get {
                return ResourceManager.GetString("AlternativelyYouCanLeaveThisFieldBlankForNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asterisk.
        /// </summary>
        public static string Asterisk {
            get {
                return ResourceManager.GetString("Asterisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullets.
        /// </summary>
        public static string Bullets {
            get {
                return ResourceManager.GetString("Bullets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Text.
        /// </summary>
        public static string CenterText {
            get {
                return ResourceManager.GetString("CenterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created At.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at {0} by {1}, last modified at {2} by {3}..
        /// </summary>
        public static string CreatedAtByModifiedAtBy {
            get {
                return ResourceManager.GetString("CreatedAtByModifiedAtBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A CSV field value may not contain quotes (&quot;) unless the whole field value is surrounded by quotes (&quot;field value&quot;) and the quotes inside are escaped with quotes (&quot;field &quot;&quot; value&quot;)..
        /// </summary>
        public static string CsvQuotesError {
            get {
                return ResourceManager.GetString("CsvQuotesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &quot;{0}&quot; cannot be set for field &quot;{1}&quot;..
        /// </summary>
        public static string CsvValueError {
            get {
                return ResourceManager.GetString("CsvValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daily.
        /// </summary>
        public static string daily {
            get {
                return ResourceManager.GetString("daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease Indent.
        /// </summary>
        public static string DecreaseIndent {
            get {
                return ResourceManager.GetString("DecreaseIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field mapping for &quot;{0}&quot; cannot be found..
        /// </summary>
        public static string FieldMappingError {
            get {
                return ResourceManager.GetString("FieldMappingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Sir or Madam,
        ///
        ///by clicking &quot;Forgot password&quot; this email was sent.
        ///
        ///If you like to reset your password, please use the following link: [link]
        ///
        ///The link will either expire after 24 hours or as soon as a new link for resetting the password is requested.
        ///
        ///Thank you very much and best regards..
        /// </summary>
        public static string ForgotPasswordMailText {
            get {
                return ResourceManager.GetString("ForgotPasswordMailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to.
        /// </summary>
        public static string GoTo {
            get {
                return ResourceManager.GetString("GoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hourly.
        /// </summary>
        public static string hourly {
            get {
                return ResourceManager.GetString("hourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprint.
        /// </summary>
        public static string Imprint {
            get {
                return ResourceManager.GetString("Imprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Indent.
        /// </summary>
        public static string IncreaseIndent {
            get {
                return ResourceManager.GetString("IncreaseIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Image.
        /// </summary>
        public static string InsertImage {
            get {
                return ResourceManager.GetString("InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Link.
        /// </summary>
        public static string InsertLink {
            get {
                return ResourceManager.GetString("InsertLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Table.
        /// </summary>
        public static string InsertTable {
            get {
                return ResourceManager.GetString("InsertTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Table Column.
        /// </summary>
        public static string InsertTableColumn {
            get {
                return ResourceManager.GetString("InsertTableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Table Row.
        /// </summary>
        public static string InsertTableRow {
            get {
                return ResourceManager.GetString("InsertTableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invariant Text.
        /// </summary>
        public static string InvariantText {
            get {
                return ResourceManager.GetString("InvariantText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invariant Title.
        /// </summary>
        public static string InvariantTitle {
            get {
                return ResourceManager.GetString("InvariantTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string Italic {
            get {
                return ResourceManager.GetString("Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (L x W x H).
        /// </summary>
        public static string LengthXWidthXHeightAbbr {
            get {
                return ResourceManager.GetString("LengthXWidthXHeightAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutely.
        /// </summary>
        public static string minutely {
            get {
                return ResourceManager.GetString("minutely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified At.
        /// </summary>
        public static string ModifiedAt {
            get {
                return ResourceManager.GetString("ModifiedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        public static string ModifiedBy {
            get {
                return ResourceManager.GetString("ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monthly.
        /// </summary>
        public static string monthly {
            get {
                return ResourceManager.GetString("monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results were found for &quot;{0}&quot;..
        /// </summary>
        public static string NoResultsWereFoundFor0 {
            get {
                return ResourceManager.GetString("NoResultsWereFoundFor0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Inspected.
        /// </summary>
        public static string NotInspected {
            get {
                return ResourceManager.GetString("NotInspected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} results were found for &quot;{0}&quot;..
        /// </summary>
        public static string NResultsWereFoundFor0 {
            get {
                return ResourceManager.GetString("NResultsWereFoundFor0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbering.
        /// </summary>
        public static string Numbering {
            get {
                return ResourceManager.GetString("Numbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is offline. It might be that outdated or incomplete data is displayed. Changes to data are not possible in all cases..
        /// </summary>
        public static string OfflineMessage {
            get {
                return ResourceManager.GetString("OfflineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One result was found for &quot;{0}&quot;..
        /// </summary>
        public static string OneResultWasFoundFor0 {
            get {
                return ResourceManager.GetString("OneResultWasFoundFor0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click &quot;Save&quot; to release the form..
        /// </summary>
        public static string PleaseClickSaveToReleaseTheForm {
            get {
                return ResourceManager.GetString("PleaseClickSaveToReleaseTheForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm the change of your preferred language by entering your Windows password..
        /// </summary>
        public static string PleaseConfirmTheChangeOfYourPreferredLanguageByEnteringYourWindowsPassword {
            get {
                return ResourceManager.GetString("PleaseConfirmTheChangeOfYourPreferredLanguageByEnteringYourWindowsPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the missing or invalid input values..
        /// </summary>
        public static string PleaseCorrectTheInvalidInputValues {
            get {
                return ResourceManager.GetString("PleaseCorrectTheInvalidInputValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a new password to change your password or leave this field empty to keep your password..
        /// </summary>
        public static string PleaseEnterANewPasswordToChangeYourPasswordOrLeaveThisFieldEmptyToKeepYourPassword {
            get {
                return ResourceManager.GetString("PleaseEnterANewPasswordToChangeYourPasswordOrLeaveThisFieldEmptyToKeepYourPasswor" +
                        "d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a unique email address for this field..
        /// </summary>
        public static string PleaseEnterAUniqueEmailAddressForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterAUniqueEmailAddressForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a unique value for this field..
        /// </summary>
        public static string PleaseEnterAUniqueValueForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterAUniqueValueForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid date and time between {0} and {1} for this field..
        /// </summary>
        public static string PleaseEnterAValidDateAndTimeBetween0And1ForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterAValidDateAndTimeBetween0And1ForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid date and time for this field..
        /// </summary>
        public static string PleaseEnterAValidDateAndTimeForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterAValidDateAndTimeForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid date between {0} and {1} for this field..
        /// </summary>
        public static string PleaseEnterAValidDateBetween0And1ForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterAValidDateBetween0And1ForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid date for this field..
        /// </summary>
        public static string PleaseEnterAValidDateForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterAValidDateForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid month between {0} and {1} for this field..
        /// </summary>
        public static string PleaseEnterAValidMonthBetween0And1ForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterAValidMonthBetween0And1ForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid month for this field..
        /// </summary>
        public static string PleaseEnterAValidMonthForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterAValidMonthForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid time between {0} and {1} for this field..
        /// </summary>
        public static string PleaseEnterAValidTimeBetween0And1ForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterAValidTimeBetween0And1ForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid time for this field..
        /// </summary>
        public static string PleaseEnterAValidTimeForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterAValidTimeForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value between {0} and {1} and a unit for this field..
        /// </summary>
        public static string PleaseEnterAValidValueBetween0And1AndAUnitForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterAValidValueBetween0And1AndAUnitForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value between {0} and {1} and select a unit for this field..
        /// </summary>
        public static string PleaseEnterAValidValueBetween0And1AndSelectAUnitForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterAValidValueBetween0And1AndSelectAUnitForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value between {0} and {1} for this field..
        /// </summary>
        public static string PleaseEnterAValidValueBetween0And1ForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterAValidValueBetween0And1ForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value for this field..
        /// </summary>
        public static string PleaseEnterAValidValueForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterAValidValueForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value greater than or equal to {0} and a unit for this field..
        /// </summary>
        public static string PleaseEnterAValidValueGreaterThan0AndAUnitForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterAValidValueGreaterThan0AndAUnitForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value greater than or equal to {0} and select a unit for this field..
        /// </summary>
        public static string PleaseEnterAValidValueGreaterThan0AndSelectAUnitForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterAValidValueGreaterThan0AndSelectAUnitForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value greater than or equal to {0} for this field..
        /// </summary>
        public static string PleaseEnterAValidValueGreaterThan0ForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterAValidValueGreaterThan0ForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value less than or equal to {0} and a unit for this field..
        /// </summary>
        public static string PleaseEnterAValidValueLessThan0AndAUnitForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterAValidValueLessThan0AndAUnitForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value less than or equal to {0} and select a unit for this field..
        /// </summary>
        public static string PleaseEnterAValidValueLessThan0AndSelectAUnitForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterAValidValueLessThan0AndSelectAUnitForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value less than or equal to {0} for this field..
        /// </summary>
        public static string PleaseEnterAValidValueLessThan0ForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterAValidValueLessThan0ForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value with at least {0} and at most {1} characters for this field..
        /// </summary>
        public static string PleaseEnterAValidValueWithAtLeast0AndAtMost1CharactersForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterAValidValueWithAtLeast0AndAtMost1CharactersForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value with at least {0} characters for this field..
        /// </summary>
        public static string PleaseEnterAValidValueWithAtLeast0CharactersForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterAValidValueWithAtLeast0CharactersForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value with at least one character for this field..
        /// </summary>
        public static string PleaseEnterAValidValueWithAtLeastOneCharacterForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterAValidValueWithAtLeastOneCharacterForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value with at most {0} characters for this field..
        /// </summary>
        public static string PleaseEnterAValidValueWithAtMost0CharactersForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterAValidValueWithAtMost0CharactersForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value with at most one character for this field..
        /// </summary>
        public static string PleaseEnterAValidValueWithAtMostOneCharacterForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterAValidValueWithAtMostOneCharacterForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid week between {0} and {1} for this field..
        /// </summary>
        public static string PleaseEnterAValidWeekBetween0And1ForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterAValidWeekBetween0And1ForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid week for this field..
        /// </summary>
        public static string PleaseEnterAValidWeekForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterAValidWeekForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid values between {0} and {1} for this field..
        /// </summary>
        public static string PleaseEnterValidValuesBetween0And1ForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterValidValuesBetween0And1ForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid values for this field..
        /// </summary>
        public static string PleaseEnterValidValuesForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterValidValuesForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid values greater than or equal to {0} for this field..
        /// </summary>
        public static string PleaseEnterValidValuesGreaterThan0ForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterValidValuesGreaterThan0ForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid values less than or equal to {0} for this field..
        /// </summary>
        public static string PleaseEnterValidValuesLessThan0ForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterValidValuesLessThan0ForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid values with at most {0} characters for this field..
        /// </summary>
        public static string PleaseEnterValidValuesWithAtMost0CharactersForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterValidValuesWithAtMost0CharactersForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid values with at most one character for this field..
        /// </summary>
        public static string PleaseEnterValidValuesWithAtMostOneCharacterForThisField {
            get {
                return ResourceManager.GetString("PleaseEnterValidValuesWithAtMostOneCharacterForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address below and click the SUBMIT button. Afterwards you will receive an email with a link you can use to reset your password..
        /// </summary>
        public static string PleaseEnterYourEmailAddressBelowAndClickTheSubmitButton {
            get {
                return ResourceManager.GetString("PleaseEnterYourEmailAddressBelowAndClickTheSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your new password below and click the SUBMIT button. Afterwards you will be able to sign in with your new password..
        /// </summary>
        public static string PleaseEnterYourNewPasswordBelowAndClickTheSubmitButton {
            get {
                return ResourceManager.GetString("PleaseEnterYourNewPasswordBelowAndClickTheSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your user name below and click the SUBMIT button. Afterwards you will receive an email with a link you can use to reset your password..
        /// </summary>
        public static string PleaseEnterYourUserNameBelowAndClickTheSubmitButton {
            get {
                return ResourceManager.GetString("PleaseEnterYourUserNameBelowAndClickTheSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please excuse that the data export takes longer than expected. To save your time, the results will be emailed to {0} once the processing is done..
        /// </summary>
        public static string PleaseExcuseThatTheDataExportTakesLongerThanExpected {
            get {
                return ResourceManager.GetString("PleaseExcuseThatTheDataExportTakesLongerThanExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please find attached the requested data export..
        /// </summary>
        public static string PleaseFindAttachedTheRequestedDataExport {
            get {
                return ResourceManager.GetString("PleaseFindAttachedTheRequestedDataExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure file names do not contain any of the following characters: &lt;, &gt;, *, %, &amp;, :, \..
        /// </summary>
        public static string PleaseMakeSureFileNamesDoNotContainAnyOfTheFollowingCharacters {
            get {
                return ResourceManager.GetString("PleaseMakeSureFileNamesDoNotContainAnyOfTheFollowingCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure the value contains at least an upper case character, a lower case character, a numeric character and a special character..
        /// </summary>
        public static string PleaseMakeSureTheValueContainsAtLeastAnUpperCaseCharacterALowerCaseCharacterANumericCharacterAndASpecialCharacter {
            get {
                return ResourceManager.GetString("PleaseMakeSureTheValueContainsAtLeastAnUpperCaseCharacterALowerCaseCharacterANume" +
                        "ricCharacterAndASpecialCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a CSV file encoded as UTF-8 with BOM..
        /// </summary>
        public static string PleaseSelectACsvFileEndodedAsUtf8WithBom {
            get {
                return ResourceManager.GetString("PleaseSelectACsvFileEndodedAsUtf8WithBom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file of an allowed type with a maximum file size of {0} MB..
        /// </summary>
        public static string PleaseSelectAFileOfAnAllowedTypeWithAMaximumFileSizeOf0MB {
            get {
                return ResourceManager.GetString("PleaseSelectAFileOfAnAllowedTypeWithAMaximumFileSizeOf0MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file with a maximum file size of {0} MB..
        /// </summary>
        public static string PleaseSelectAFileWithAMaximumFileSizeOf0MB {
            get {
                return ResourceManager.GetString("PleaseSelectAFileWithAMaximumFileSizeOf0MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid person for this field..
        /// </summary>
        public static string PleaseSelectAValidPersonForThisField {
            get {
                return ResourceManager.GetString("PleaseSelectAValidPersonForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid value for this field..
        /// </summary>
        public static string PleaseSelectAValidValueForThisField {
            get {
                return ResourceManager.GetString("PleaseSelectAValidValueForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select files of allowed typed with a maximum file size of {0} MB each..
        /// </summary>
        public static string PleaseSelectFilesOfAllowedTypesWithAMaximumFileSizeOf0MB {
            get {
                return ResourceManager.GetString("PleaseSelectFilesOfAllowedTypesWithAMaximumFileSizeOf0MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select files with a maximum file size of {0} MB each..
        /// </summary>
        public static string PleaseSelectFilesWithAMaximumFileSizeOf0MB {
            get {
                return ResourceManager.GetString("PleaseSelectFilesWithAMaximumFileSizeOf0MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one or more valid persons for this field..
        /// </summary>
        public static string PleaseSelectOneOrMoreValidPersonsForThisField {
            get {
                return ResourceManager.GetString("PleaseSelectOneOrMoreValidPersonsForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one or more valid values for this field..
        /// </summary>
        public static string PleaseSelectOneOrMoreValidValuesForThisField {
            get {
                return ResourceManager.GetString("PleaseSelectOneOrMoreValidValuesForThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the plus button to add translations..
        /// </summary>
        public static string PleaseUseThePlusButtonToAddTranslations {
            get {
                return ResourceManager.GetString("PleaseUseThePlusButtonToAddTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the LOGIN button to log on. Please use your email address as user name. If you do not remember your password, please click the FORGOT PASSWORD button..
        /// </summary>
        public static string PleaseUseTheSignInButtonToLogOnWithYourEmailAddress {
            get {
                return ResourceManager.GetString("PleaseUseTheSignInButtonToLogOnWithYourEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the LOGIN button to log on with you user name and password. If you do not remember your password, please click the FORGOT PASSWORD button..
        /// </summary>
        public static string PleaseUseTheSignInButtonToLogOnWithYourUserName {
            get {
                return ResourceManager.GetString("PleaseUseTheSignInButtonToLogOnWithYourUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Culture.
        /// </summary>
        public static string PreferredCulture {
            get {
                return ResourceManager.GetString("PreferredCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Language.
        /// </summary>
        public static string PreferredLanguage {
            get {
                return ResourceManager.GetString("PreferredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Notice.
        /// </summary>
        public static string PrivacyNotice {
            get {
                return ResourceManager.GetString("PrivacyNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue Length.
        /// </summary>
        public static string QueueLength {
            get {
                return ResourceManager.GetString("QueueLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Marks.
        /// </summary>
        public static string QuotationMarks {
            get {
                return ResourceManager.GetString("QuotationMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate {0} star(s)..
        /// </summary>
        public static string Rate0Stars {
            get {
                return ResourceManager.GetString("Rate0Stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        public static string References {
            get {
                return ResourceManager.GetString("References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Format.
        /// </summary>
        public static string RemoveFormat {
            get {
                return ResourceManager.GetString("RemoveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Link.
        /// </summary>
        public static string RemoveLink {
            get {
                return ResourceManager.GetString("RemoveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Table Column.
        /// </summary>
        public static string RemoveTableColumn {
            get {
                return ResourceManager.GetString("RemoveTableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Table Row.
        /// </summary>
        public static string RemoveTableRow {
            get {
                return ResourceManager.GetString("RemoveTableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results {0} to {1} are displayed below..
        /// </summary>
        public static string Results0To1AreDisplayedBelow {
            get {
                return ResourceManager.GetString("Results0To1AreDisplayedBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the search operator AND results can be found that contain all entered terms as whole words. The following seach query will find all results that contain the word &quot;needle&quot; as well as the word &quot;haystack&quot;:.
        /// </summary>
        public static string SearchHelpAndDescription {
            get {
                return ResourceManager.GetString("SearchHelpAndDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to needle AND haystack.
        /// </summary>
        public static string SearchHelpAndExample {
            get {
                return ResourceManager.GetString("SearchHelpAndExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the search operator AND NOT results can be found that contain a specific term as whole word, but may not contain another term. The following seach query will find all results that contain the word &quot;needle&quot; but not the word &quot;haystack&quot;:.
        /// </summary>
        public static string SearchHelpAndNotDescription {
            get {
                return ResourceManager.GetString("SearchHelpAndNotDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to needle AND NOT haystack.
        /// </summary>
        public static string SearchHelpAndNotExample {
            get {
                return ResourceManager.GetString("SearchHelpAndNotExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case of a seach term within quotation marks starts/ends with an asterisk character, results can be found that contain the ending/beginning of that term. The following seach query will find all results containing the expression &quot;haystack&quot; as well as ones containing the expression &quot;hayfork&quot;:.
        /// </summary>
        public static string SearchHelpAsteriskCharaktersDescription {
            get {
                return ResourceManager.GetString("SearchHelpAsteriskCharaktersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;hay*&quot;.
        /// </summary>
        public static string SearchHelpAsteriskCharaktersExample {
            get {
                return ResourceManager.GetString("SearchHelpAsteriskCharaktersExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the search operator OR results can be found that contain any of the entered terms as whole words. The following seach query will find all results that either contain the word &quot;needle&quot; or the word &quot;haystack&quot;:.
        /// </summary>
        public static string SearchHelpOrDescription {
            get {
                return ResourceManager.GetString("SearchHelpOrDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to needle OR haystack.
        /// </summary>
        public static string SearchHelpOrExample {
            get {
                return ResourceManager.GetString("SearchHelpOrExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search terms entered within quotation marks have to be in the result in the exact same order. The following seach query will find all results containing the phrase &quot;needle in haystack&quot;, but would not find any result containing the phrase &quot;needle in the haystack&quot; only instead:.
        /// </summary>
        public static string SearchHelpQuotationMarksDescription {
            get {
                return ResourceManager.GetString("SearchHelpQuotationMarksDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;needle in haystack&quot;.
        /// </summary>
        public static string SearchHelpQuotationMarksExample {
            get {
                return ResourceManager.GetString("SearchHelpQuotationMarksExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to secondly.
        /// </summary>
        public static string secondly {
            get {
                return ResourceManager.GetString("secondly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikethrough.
        /// </summary>
        public static string Strikethrough {
            get {
                return ResourceManager.GetString("Strikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscript.
        /// </summary>
        public static string Subscript {
            get {
                return ResourceManager.GetString("Subscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superscript.
        /// </summary>
        public static string Superscript {
            get {
                return ResourceManager.GetString("Superscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Color.
        /// </summary>
        public static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action for &quot;{0}&quot; cannot be executed because it is ambiguous. Please use the button &quot;{0}&quot; of the desired step in the workflow diagram to execute the action. Would you like to see the workflow diagram?.
        /// </summary>
        public static string TheActionFor0CannotBeExecutedBecauseItIsAmbiguous {
            get {
                return ResourceManager.GetString("TheActionFor0CannotBeExecutedBecauseItIsAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered combination of user name and password is invalid..
        /// </summary>
        public static string TheEnteredCombinationOfUserNameAndPasswordIsInvalid {
            get {
                return ResourceManager.GetString("TheEnteredCombinationOfUserNameAndPasswordIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first {0} results are displayed below..
        /// </summary>
        public static string TheFirst0ResultsAreDisplayedBelow {
            get {
                return ResourceManager.GetString("TheFirst0ResultsAreDisplayedBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum image resolution must be {0} x {1}..
        /// </summary>
        public static string TheMinimumImageResolutionMustBe0x1 {
            get {
                return ResourceManager.GetString("TheMinimumImageResolutionMustBe0x1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum side length of longer side of image must be {0}..
        /// </summary>
        public static string TheMinimumImageSideLengthOfLongerSideMustBe0 {
            get {
                return ResourceManager.GetString("TheMinimumImageSideLengthOfLongerSideMustBe0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected value does not have a unique key..
        /// </summary>
        public static string TheSelectedValueDoesNotHaveAUniqueKey {
            get {
                return ResourceManager.GetString("TheSelectedValueDoesNotHaveAUniqueKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow will go on as soon as the step &quot;{0}&quot; is finished..
        /// </summary>
        public static string TheWorkflowWillGoOnAsSoonAsTheStep0IsFinished {
            get {
                return ResourceManager.GetString("TheWorkflowWillGoOnAsSoonAsTheStep0IsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a mandatory field..
        /// </summary>
        public static string ThisIsAMandatoryField {
            get {
                return ResourceManager.GetString("ThisIsAMandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Full Window.
        /// </summary>
        public static string ToggleFullWindow {
            get {
                return ResourceManager.GetString("ToggleFullWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many requests. Please try again in {0} seconds..
        /// </summary>
        public static string TooManyRequestsPleaseTryAgainIn0Seconds {
            get {
                return ResourceManager.GetString("TooManyRequestsPleaseTryAgainIn0Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated Text.
        /// </summary>
        public static string TranslatedText {
            get {
                return ResourceManager.GetString("TranslatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        public static string Underline {
            get {
                return ResourceManager.GetString("Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to {0} files are allowed..
        /// </summary>
        public static string UpTo0FilesAreAllowed {
            get {
                return ResourceManager.GetString("UpTo0FilesAreAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to {0} values are allowed..
        /// </summary>
        public static string UpTo0ValuesAreAllowed {
            get {
                return ResourceManager.GetString("UpTo0ValuesAreAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weekly.
        /// </summary>
        public static string weekly {
            get {
                return ResourceManager.GetString("weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow.
        /// </summary>
        public static string Workflow {
            get {
                return ResourceManager.GetString("Workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you really like to delete the row?.
        /// </summary>
        public static string WouldYouReallyLikeToDeleteTheRow {
            get {
                return ResourceManager.GetString("WouldYouReallyLikeToDeleteTheRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you really like to delete the tab &quot;{0}&quot;?.
        /// </summary>
        public static string WouldYouReallyLikeToDeleteTheTab {
            get {
                return ResourceManager.GetString("WouldYouReallyLikeToDeleteTheTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you really like to mark the file &quot;{0}&quot; for removal?.
        /// </summary>
        public static string WouldYouReallyLikeToMarkTheFile0ForRemoval {
            get {
                return ResourceManager.GetString("WouldYouReallyLikeToMarkTheFile0ForRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yearly.
        /// </summary>
        public static string yearly {
            get {
                return ResourceManager.GetString("yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has expired. Please enter a new password below and click the SUBMIT button. The new password has to be different from the previous one. Afterwards you will be able to sign in with your new password..
        /// </summary>
        public static string YourPasswordHasExpiredPleaseEnterANewPasswordBelowAndClickTheSubmitButton {
            get {
                return ResourceManager.GetString("YourPasswordHasExpiredPleaseEnterANewPasswordBelowAndClickTheSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has to be changed at first logon. Please enter a new password below and click the SUBMIT button. The new password has to be different from the initialone. Afterwards you will be able to sign in with your new password..
        /// </summary>
        public static string YourPasswordHasToBeChangedAtFirstLogonPleaseEnterANewPasswordBelowAndClickTheSubmitButton {
            get {
                return ResourceManager.GetString("YourPasswordHasToBeChangedAtFirstLogonPleaseEnterANewPasswordBelowAndClickTheSubm" +
                        "itButton", resourceCulture);
            }
        }
    }
}
